# PyTorch Basic

PyTorch 기초 사용법

In [2]:
import numpy as np

import torch

In [ ]:
nums = torch.arange(9)

In [ ]:
nums.shape

In [ ]:
type(nums)

In [ ]:
nums.numpy()

In [ ]:
nums.reshape(3, 3)

In [ ]:
randoms = torch.rand((3, 3))

In [ ]:
randoms

In [ ]:
zeros = torch.zeros((3, 3))

In [ ]:
zeros

In [ ]:
zeros.size()

# Operations

PyTorch로 수학연산

In [ ]:
nums * 3

In [ ]:
nums = nums.reshape((3, 3))

In [ ]:
nums + nums

In [ ]:
torch.add(nums, 10)

## View

In [ ]:
range_nums = torch.arange(9).reshape(3,3)

In [ ]:
range_nums

In [ ]:
range_nums.view(-1)

In [ ]:
range_nums.view(1,9)

# Slice and Index

In [ ]:
nums

In [ ]:
nums[1]

In [ ]:
nums[1, 1]

In [ ]:
nums[1:, 1:]

## Compile

numpy를 torch tensor로 불러오기

In [ ]:
arr = np.array([1, 1, 1])


In [ ]:
arr_torch = torch.from_numpy(arr)

In [ ]:
arr_torch.float()

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [ ]:
arr_torch.to(device)

In [ ]:
device

# AutoGrad

In [3]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y = x + 2

In [5]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
z = y * y * 3
out = z.mean()

In [7]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [8]:
out.backward()

In [9]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [10]:
print(x.requires_grad)
print((x**2).requires_grad)

True
True


In [12]:
with torch.no_grad():
    print((x ** 2).requires_grad)

False
