In [1]:
import tensorflow as tf

/Users/afraca/Documents/deep-base/venv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/afraca/Documents/deep-base/venv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/afraca/Documents/deep-base/venv/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/afraca

In [2]:
tf.__version__

'2.2.0'

In [3]:
import torch

## base

In [4]:
x = 1
y = 3
z = x+y

In [6]:
print('hello')

hello


In [7]:
import numpy as np

In [8]:
arr = np.array(5)

In [9]:
arr.shape

()

In [10]:
arr.ndim

0

In [11]:
arr = np.array([5])
arr

array([5])

In [12]:
arr.shape

(1,)

In [13]:
arr.ndim

1

In [15]:
arr = np.array([[1,2,3]])
arr.shape

(1, 3)

In [16]:
arr = np.array([[1,2,3],[1,2,3],[1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [17]:
arr.shape

(3, 3)

In [18]:
arr.ndim

2

## zeros & ones

In [19]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
zeros = np.zeros([1])
zeros

array([0.])

In [22]:
ones = np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [24]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [26]:
arr = np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [28]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## index

In [32]:
nums = [1,2,3,4,5]

In [33]:
nums[2:]

[3, 4, 5]

In [36]:
nums = [1,2,3,4,[1,2,3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [37]:
nums[4]

[1, 2, 3]

In [38]:
arr[1][2]

5

## slicing

In [39]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [41]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

## boolean indexing

In [43]:
data = np.random.randn(3,3)
data

array([[-1.66751831,  0.8094346 , -0.7512352 ],
       [ 0.57347112, -0.62300199, -1.25619846],
       [-1.41941979, -0.27989826,  0.23835936]])

In [44]:
data <= 0

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [47]:
data[data <= 0] = 1
data

array([[1.        , 0.8094346 , 1.        ],
       [0.57347112, 1.        , 1.        ],
       [1.        , 1.        , 0.23835936]])

## broadcast

In [48]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [50]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## math function

In [51]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [52]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [53]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [54]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [57]:
arr = np.random.randint(2, size=27).reshape(3,3,3)
arr_2 = np.random.randint(2, size=9).reshape(3,3)

In [58]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [59]:
arr, arr_2

(array([[[1, 1, 0],
         [1, 1, 1],
         [1, 0, 1]],
 
        [[1, 1, 1],
         [1, 0, 1],
         [1, 1, 1]],
 
        [[0, 1, 0],
         [0, 1, 1],
         [0, 0, 1]]]),
 array([[1, 1, 0],
        [0, 0, 1],
        [1, 1, 0]]))

In [60]:
arr + arr_2

array([[[2, 2, 0],
        [1, 1, 2],
        [2, 1, 1]],

       [[2, 2, 1],
        [1, 0, 2],
        [2, 2, 1]],

       [[1, 2, 0],
        [0, 1, 2],
        [1, 1, 1]]])

In [61]:
arr * arr_2

array([[[1, 1, 0],
        [0, 0, 1],
        [1, 0, 0]],

       [[1, 1, 0],
        [0, 0, 1],
        [1, 1, 0]],

       [[0, 1, 0],
        [0, 0, 1],
        [0, 0, 0]]])

In [62]:
np.sum(arr)

19

In [63]:
np.sum(arr+arr_2)

34

In [64]:
arr + arr_2

array([[[2, 2, 0],
        [1, 1, 2],
        [2, 1, 1]],

       [[2, 2, 1],
        [1, 0, 2],
        [2, 2, 1]],

       [[1, 2, 0],
        [0, 1, 2],
        [1, 1, 1]]])

In [66]:
np.min(arr + arr_2)

0

In [71]:
np.sum(arr+arr_2, 0)

array([[5, 6, 1],
       [2, 2, 6],
       [5, 4, 3]])

In [74]:
np.sum(arr + arr_2, -1)

array([[4, 4, 4],
       [5, 3, 5],
       [3, 3, 3]])

In [75]:
arr = np.array([1,3,6,7,9,2,3,0,5])

In [76]:
np.argmax(arr)

4

In [77]:
np.argmin(arr)

7

In [78]:
np.unique(arr)

array([0, 1, 2, 3, 5, 6, 7, 9])