# Numpy basic 2

In [1]:
import numpy as np

## data type

In [2]:
arr = np.array([[1,2,3], [1,2,3]])

In [3]:
arr.dtype

dtype('int64')

In [5]:
arr.astype('int8')

array([[1, 2, 3],
       [1, 2, 3]], dtype=int8)

In [7]:
arr = np.array([[1,2,3],[1,2,3]], dtype=np.uint8)

In [8]:
arr.dtype

dtype('uint8')

In [9]:
len(arr.shape)

2

In [10]:
arr.shape

(2, 3)

## Reshape

In [12]:
arr.reshape([1, 6])

array([[1, 2, 3, 1, 2, 3]], dtype=uint8)

In [13]:
arr = np.array([[1,2,3], [1,2,3]])

In [15]:
arr.reshape([6]).shape

(6,)

In [17]:
arr.reshape(-1)

array([1, 2, 3, 1, 2, 3])

In [23]:
arr = arr.reshape(1, -1)
arr.shape
arr

array([[1, 2, 3, 1, 2, 3]])

In [25]:
arr = np.random.randn(8,8)
arr.shape

(8, 8)

In [28]:
arr = arr.reshape([32,2])
arr.shape

(32, 2)

In [29]:
arr

array([[-0.21043899,  0.17393556],
       [ 0.43247976,  1.99391176],
       [ 0.02139038,  2.34102716],
       [ 0.5815221 ,  1.02087433],
       [ 1.02053318, -0.27415817],
       [ 0.54224203, -1.7794733 ],
       [-1.36782862, -2.41127625],
       [ 0.40950414,  0.7744399 ],
       [ 0.95014735, -2.1039997 ],
       [-0.364898  , -2.15972999],
       [ 0.04007977, -0.03010736],
       [-0.28624797, -0.66157485],
       [ 0.39098628, -0.78648801],
       [-0.11760777,  0.41825431],
       [ 1.8967795 , -1.0114807 ],
       [ 0.29902554, -2.36393289],
       [-0.5469839 ,  1.14733002],
       [-1.15031339,  0.88399824],
       [-1.52785366, -0.23688382],
       [ 0.81052984, -1.99479283],
       [-1.05081585, -0.73367397],
       [-1.89456869,  1.33977489],
       [-0.13943958, -0.47724963],
       [-0.81618803,  0.23302148],
       [-1.36237379,  0.3802831 ],
       [ 1.19103887,  1.17433763],
       [ 1.28295682, -0.43139226],
       [-0.26769642,  1.04206811],
       [ 0.74692085,

In [31]:
arr = arr.reshape(-1, 2, 1)
arr.shape

(32, 2, 1)

## Ravel

In [32]:
arr.shape

(32, 2, 1)

In [33]:
arr = arr.ravel()
arr.shape

(64,)

In [34]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

### np.expand_dims()
안의 값은 유지하되 차원 수를 늘리고 싶을 떄가 있음 이럴떄 사용하는 것이 expand_dims

In [35]:
arr.shape

(64,)

In [39]:
arr = np.expand_dims(arr, 0)

In [40]:
arr.shape

(1, 64, 1)